// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erwelgqvilhgtqorxwnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyd2VsZ3F2aWxoZ3Rxb3J4d25mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDg2OTQsImV4cCI6MjA2NDc4NDY5NH0.uFxR65Pt7iha84iKY37p-axHL9rR8UKAMsyKVnOnZO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);